### PR TITLE
enable password authentication

### PR DESCRIPTION
**Pull request by gordon00**
Add the hability to protect x11vnc with one or several passwords

### CODE REVIEW

**Comment by realies** [comment]
Thanks for the PR. Wondering why do we need the python3 dependency? Also, wouldn't it be better/more secure to expose this service through a reverse proxy instead of having a password for the VNC server within the container? Access to log files and downloaded files would still be possible through the menu on the left, despite the VNC server password.

**Comment by gordon00** [comment]
I tried my modifications with "docker build ." But the novnc service was looping because of missing dependency.
I was surprised so i reverted my work et rebuild the image to check if I was responsible of that behavior,  but I had the same problem. When I had the python3 dependency installed, the container starts normally.

I am going to explain my need for the password directly with x11vnc :
First I configured my nginx reverse proxy with a static basic auth. It does the job.
But when I don't have access to any computer, I use my smartphone. And the web client experience is juste awful. (Typin, scaling, moving, clicking... )

So I exposed directly the 5900 port and use the VncViewer application on android. It's much better but lacked minimum security...

Does it sound usefull for other users ?

**Comment by realies** [comment]
It could be that they have removed python3 from `ubuntu:bionic`. The use of another VNC client is a good reason for the change, we might have to add some disclaimers on security. Will try to verify the changes and push an update soon.

**Comment by gordon00** [comment]
Great thank you.

My novnc access is secured by ssl nginx reverse proxy with letsencrypt certificate but yeah I was a little concerned by opening the VNC port with clear password protection. Do you suggest any more secured way ?

Just for your information. When I use the web interface, I don't have access to the download button until I got logged in.

Screenshot before login, left panel buttons are disabled : 
image

But if you know the direct url (/downloads) it won't be protected. You have to combine with basic auth at reverse proxy level.

That said, I don't really use the downloads link because my soulseek download volume is directly linked to my airsonic container and I directly stream files using airsonic on server side and subsonic android app on client side.

**Pull request merged**
